name: Docker Build and Test

# 1. When should this run?
on:
    workflow_dispatch:
    push:
        branches: [ "main" ] # Runs Whenever you push to the main branch

jobs:
    build-and-test:
        runs-on: ubuntu-latest # This starts a fresh Linux machine in the cloud

        steps:
            - name: Checkout code
              uses: actions/checkout@v4 # This copies your code to the cloud machine

            - name: Build the Docker image
              run: docker build -t my-web-app . 

            - name: Verify Container Starts
              run: |
                docker run -d -p 8080:3000 --name test-container my-web-app
                sleep 5
                docker ps | grep test-container

            - name: Deploy to AWS
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.HOST }}
                username: ${{ secrets.USERNAME }}
                key: ${{ secrets.SSH_KEY }}
                script: | 
                  # Stop any old version of the app
                  docker stop my-web-app || true
                  docker rm my-web-app || true
                  #Pull the new code and run it
                  docker build -t my-web-app .
                  docker run -d -p 80:3000 --name my-web-app my-wep-app 

